# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Typist
version:      0.02
version_from: lib/Typist.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0
    Class::ErrorHandler:           0
    File::Spec:                    0
    Locale::Maketext:              0
    Tie::IxHash:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
